In [3]:
# Create a 1D NumPy array with 10 elements, containing the numbers from 1 to 10.

import numpy as np
array1=np.arange(1,11)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
# Create a 2D NumPy array of shape (3, 4) filled with ones.

array2=np.arange(1,13)
array2=np.copy(array2.reshape(3,4))
array2[array2 > 1] = 1
print(array2)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
# Create a 3x3 identity matrix using NumPy.

martrix3=np.arange(20,29).reshape(3,3)
print(martrix3)

[[20 21 22]
 [23 24 25]
 [26 27 28]]


In [ ]:
# Add 5 to each element in a 1D NumPy array: [1, 2, 3, 4, 5].

array3=np.arange(1,6)
print("Original 1D array:\n",array3)
print("Array after adding 5 to each elements:\n",array3 + 5)

Original 1D array:
 [1 2 3 4 5]
Array after adding 5 to each elements:
 [ 6  7  8  9 10]


In [36]:
# Multiply each element in a 1D NumPy array: [2, 4, 6, 8, 10] by 2.

arrayA=np.arange(2,11)
even=arrayA[arrayA % 2 == 0]
print("Original array:\n",even)
print("Array after multiplying 2 to each elements:\n",even*2)

Original array:
 [ 2  4  6  8 10]
Array after multiplying 2 to each elements:
 [ 4  8 12 16 20]


In [35]:
#Subtract 3 from each element in a NumPy array: [6, 8, 10, 12, 14].

arrayB=np.arange(6,15)
evenB=arrayB[arrayB % 2 == 0]
print("Original array:\n",even1)
print("Array after subtracting 3 to each elements:\n",evenB-3)


Original array:
 [ 6  8 10 12 14]
Array after subtracting 3 to each elements:
 [ 3  5  7  9 11]


In [43]:
#Given a 1D array arr = np.array([10, 20, 30, 40, 50]), access the third element.

arr=np.arange(10,51)
arr2=arr[arr%10==0]
print("The 1D array is:\n",arr2)
print("The third element is:\n",arr2[2])

The 1D array is:
 [10 20 30 40 50]
The third element is:
 30


In [48]:
#Slice a 1D array to get the first 3 elements

arrX=np.arange(1,11)
print("The 1D array is:\n",arrX)
print("The first three elements are:\n",arrX[0:3])

The 1D array is:
 [ 1  2  3  4  5  6  7  8  9 10]
The first three elements are:
 [1 2 3]


In [55]:
#Given a 2D array, extract the element from the second row and third column.

arrY=np.arange(1,13)
reshaped=np.copy(arrY.reshape(3,4))
print("The 2D array is:\n",reshaped)
print("The element from second row Third column is:\n",reshaped[1,2])


The 2D array is:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The element from second row Third column is:
 7


In [ ]:
#Find the minimum and maximum value in a NumPy array: arr = np.array([2, 4, 6, 8, 10]).

arrZ = np.arange(2,11)
newarray=arrZ[arrZ % 2 == 0]
print("The array is:\n",newarray)
print("The minimum value is:\n",np.min(newarray))
print("The maximum value is:\n",np.max(newarray))

The array is:
 [ 2  4  6  8 10]
The minimum value is:
 2
The maximum value is:
 10


In [64]:
#Calculate the sum and mean of the array: arr = np.array([3, 5, 7, 9]).

arrW = np.arange(3,10)
newarrayA=arrW[arrW % 2 != 0]
print("The array is:\n",newarrayA)
print("The sum value is:\n",np.sum(newarrayA))
print("The mean value is:\n",np.mean(newarrayA))

The array is:
 [3 5 7 9]
The sum value is:
 24
The mean value is:
 6.0


In [5]:
#Reshape a 1D array arr = np.array([1, 2, 3, 4, 5, 6]) into a 2D array of shape (2,3)

ODarray=np.arange(1,7)
print("The 1D array is:\n",ODarray)
TDarray=np.copy(ODarray.reshape(2,3))
print("A 2D array of shape (2,3) is:\n",TDarray)

The 1D array is:
 [1 2 3 4 5 6]
A 2D array of shape (2,3) is:
 [[1 2 3]
 [4 5 6]]


In [ ]:
# Flatten a 2D array arr = np.array([[1, 2, 3], [4, 5, 6]]) into a 1D array.

flattened_array = TDarray.flatten()
print(flattened_array)

[1 2 3 4 5 6]


In [ ]:
#Stack two 1D arrays [1, 2, 3] and [4, 5, 6] vertically and horizontally.

x=np.array([1,2,3])
y=np.array([4,5,6])

# Stacking these two 1D array vertically
z=np.stack((x,y),axis=1)
print("Vertical stacking:\n",z)

# Stacking these two 1D array horizontally
z=np.stack((x,y),axis=0)
print("Horizontal stacking:\n",z)

Vertical stacking:
 [[1 4]
 [2 5]
 [3 6]]
Horizontal stacking:
 [[1 2 3]
 [4 5 6]]


In [13]:
#Perform element-wise addition and subtraction on two arrays: arr1 = np.array([2, 4, 6]) and arr2 = np.array([1, 3, 5]).

arrayX=np.array([2,4,6])
arrayY=np.array([1,3,5])
print("Element wise addition on two array:\n",arrayX+arrayY)
print("Element wise subtraction on two array:\n",arrayX-arrayY)

Element wise addition on two array:
 [ 3  7 11]
Element wise subtraction on two array:
 [1 1 1]


In [16]:
#Perform element-wise multiplication and division on two arrays: arr1 = np.array([2, 4, 6]) and arr2 = np.array([1, 2, 3]).

arrayX1=np.array([2,4,6])
arrayY1=np.array([1,2,3])
print("Element wise multiplication on two array:\n",arrayX1*arrayY1)
print("Element wise division on two array:\n",arrayX1/arrayY1)

Element wise multiplication on two array:
 [ 2  8 18]
Element wise division on two array:
 [2. 2. 2.]


In [ ]:
#Calculate the dot product of two 1D arrays: arr1 = np.array([1, 2]) and arr2 = np.array([3, 4]).
a=np.array([1,2])
b=np.array([3,4])
print("Dot product of two 1D array:\n",np.dot(a,b))

Dot product of two matrices:
 11


In [26]:
#Multiply two matrices using np.dot(). Given matrices A = np.array([[1, 2], [3, 4]]) and B = np.array([[5, 6], [7, 8]]), compute their dot product.
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("Dot product of two matrices:\n",np.dot(A,B))

Dot product of two matrices:
 [[19 22]
 [43 50]]


In [37]:
#Generate an array of 10 random numbers between 0 and 1 using np.random.rand().

N=np.random.rand(1,10)
print(N)

[[0.29598512 0.71513608 0.20086422 0.92508663 0.41589307 0.55962313
  0.30366461 0.31304259 0.69243616 0.42707242]]


In [40]:
#Create a random integer array with values between 1 and 100, and of size 5 using np.random.randint().

M=np.random.randint(1,100,size=(1,5))
print(M)


[[68 85 18 24 44]]


In [ ]:
#Compare two arrays element-wise: arr1 = np.array([1, 2, 3]) and arr2 = np.array([3, 2, 1]). Find which elements in arr1 are greater than arr2.

i=np.array([1,2,3])
j=np.array([3,2,1])
comp=(i>j)
print(comp)
print("The greater element is:\n",i[2])

[False False  True]
The greater element is:
 3


In [56]:
#Use np.sum(), np.mean(), and np.std() to compute the sum, mean, and standard deviation of the array arr = np.array([10, 20, 30, 40, 50]).

K=np.array([10,20,30,40,50])
print("The sum of elements of the array is:\n",np.sum(K))
print("The mean of elements of the array is:\n",np.mean(K))
print("The Standard Deviation of elements of the array is:\n",np.std(K))

The sum of elements of the array is:
 150
The mean of elements of the array is:
 30.0
The Standard Deviation of elements of the array is:
 14.142135623730951


In [57]:
#Find the index of the maximum value in a NumPy array arr = np.array([5, 2, 8, 1, 6]) using np.argmax().

L=np.array([5,2,8,1,6])
print("The index of the maximum value is:\n",np.argmax(L))

The index of the maximum value is:
 2


In [59]:
#Add a 1D array [1, 2, 3] to a 2D array [[10, 20, 30], [40, 50, 60]] using broadcasting.

OD=np.array([1,2,3])
TD=np.array([[10,20,30],[40,50,60]])
print("Adding 1D array to 2D array using boardcasting:\n",OD+TD)

Adding 1D array to 2D array using boardcasting:
 [[11 22 33]
 [41 52 63]]
