In [2]:
import numpy as np

#Create a numpy narray using python list
a=[1,2,3,4,5,6]
type(a)
numpy_a=np.array(a)
type(numpy_a)

numpy.ndarray

In [ ]:
#Create two 2*2 matrices with random 
matrix1=np.random.randint(10,50,(2,2))
matrix2=np.random.randint(10,50,(2,2))
print(matrix1)
print(matrix2)

[[12 31]
 [45 45]]
[[40 30]
 [34 42]]


In [5]:
print("Addition:\n",matrix1+matrix2)
print("Sub:\n",matrix1-matrix2)
print("Multiply:\n",matrix1*matrix2)
print("Divide:\n",matrix1/matrix2)

Addition:
 [[52 61]
 [79 87]]
Sub:
 [[-28   1]
 [ 11   3]]
Multiply:
 [[ 480  930]
 [1530 1890]]
Divide:
 [[0.3        1.03333333]
 [1.32352941 1.07142857]]


In [6]:
dot_product=np.dot(matrix1,matrix2)
print("Dot product:\n",dot_product)

Dot product:
 [[1534 1662]
 [3330 3240]]


In [8]:
#row wise mean
print(matrix1.mean(axis=1))

[21.5 45. ]


In [9]:
#column wise mean
print(matrix1.mean(axis=0))

[28.5 38. ]


In [11]:
import pandas as pd

In [13]:
#Create a dataframe

data={
    'Name': ['Alice','Bob','Charlie','David','Eve'],
    'Math':[85,90,78,88,92],
    'Science':[80,85,89,92,91],
    'English':[85,90,78,88,92]
}
print(data)

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'], 'Math': [85, 90, 78, 88, 92], 'Science': [80, 85, 89, 92, 91], 'English': [85, 90, 78, 88, 92]}
